Update CI target OSes
gbdev/rgbds pull request #1083
Opened 2022-10-01 18:48 UTC by ISSOtm

- Remove platforms deprecated by GitHub Actions
- Add new platforms supported by the same

Fixes #785

2022-10-01 18:50 UTC, ISSOtm commented
To fix:
- [ ] 32-bit cross-build yields bad executables, and I'm not sure why.
- [ ] Is `libstdc++-6.dll` required by the new 32-bit build ?

2022-10-02 01:09 UTC, Rangi42 requested changes
`rgbds-canary-mingw-win32` works, but `rgbds-canary-mingw-win64` is missing `libstd++-6.dll`.

The win32 zip includes `libgcc_s_dw2-1.dll`, `libssp-0.dll`, and `libstdc++-6.dll`, which the win64 zip does not.

Running rgbds-canary-mingw-win64's `.\rgbgfx`:

![image](https://user-images.githubusercontent.com/35663410/193433744-45237c5c-5d04-4679-a9f0-8ba94a97336a.png)

2022-10-02 06:49 UTC, Rangi42 commented
Tried again after re-running CI and they both work now. Maybe I downloaded the wrong zip, or an outdated one, at first.

2022-10-02 06:50 UTC, Rangi42 approved these changes

2022-10-02 06:50 UTC, merged