Allow multiple identical exported numeric constants
gbdev/rgbds pull request #1341
Opened 2024-03-09 17:03 UTC by Rangi42

This does not allow identical exported label constants, which *is* possible using a WRAM SECTION UNION. That can be addressed when or if it's requested for a real use case.

Symbols only store one source filename + line number, so this arbitrarily keeps the last read symbol as the reported one.

Fixes #1340

2024-03-09 18:16 UTC, Rangi42 commented
@eievui5 Interested in your review as well.

2024-03-10 18:33 UTC, ISSOtm requested changes
Do you mind also testing that `SECTION UNION "..."` labels are not fused? Remember that constants are implemented in some places as "labels without a section".

2024-03-10 19:40 UTC, Rangi42 commented
> Do you mind also testing that `SECTION UNION "..."` labels are not fused? Remember that constants are implemented in some places as "labels without a section".

Turns out they're not fused, but they *are* already allowed, with quirky results. #1349 covers this. We should figure out what result we actually want.

2024-03-10 20:46 UTC, ISSOtm commented
As mentioned in that PR, they aren't fused because they aren't exported. This PR is concerned with *exported* constants, though.

2024-03-11 02:10 UTC, eievui5 commented
As far as I can tell this is working just fine, but I can't launch my ROM at the moment due to #1350

2024-03-13 18:06 UTC, merged