Use standard bit builtins instead of compiler extensions
gbdev/rgbds pull request #1383
Opened 2024-03-27 22:10 UTC by ISSOtm

2024-03-27 22:55 UTC, Rangi42 requested changes
Nice, thank you! Always good to see LoC go down. :)

2024-03-27 22:55 UTC, Rangi42 commented on src/fix/main.cpp
> +		nbBanks = uint32_t(1) << logNbBanks;
Everywhere else uses C-style casts; we could consider converting those to constructors separately.
```suggestion
		nbBanks = (uint32_t)1 << logNbBanks;
```

2024-03-27 22:55 UTC, Rangi42 commented on src/fix/main.cpp
> +		auto logNbBanks = std::bit_width(nbBanks - 1);
It definitely returns an [`int`](https://en.cppreference.com/w/cpp/numeric/bit_width).
```suggestion
		int logNbBanks = std::bit_width(nbBanks - 1);
```

2024-03-27 22:57 UTC, Rangi42 commented
Ubuntu 20.04's g++ 9.3.0 doesn't support `std::bit_width`. :(

2024-03-27 23:22 UTC, ISSOtm commented
Yeah, that sucks. How should we detect it, though? :/

2024-03-27 23:46 UTC, Rangi42 commented
We could directly check the `__GNUC__ ` version?

2024-03-28 00:56 UTC, ISSOtm commented
Honestly, at that point we'd be back to square one. Let's not; we can revive this PR later, after updating our requirements.

2024-03-28 00:56 UTC, closed without merging