Implement state file output for RGBASM
gbdev/rgbds pull request #1435
Opened 2024-08-03 04:58 UTC by Rangi42

Fixes #606 

Output for `EQU` constants, variables, and `EQUS` constants works.

Still to do:

- [ ] Actually parse the command line arg, instead of hard-coding output of the three working features to stdout. (Don't forget to support "`all`".)
- [ ] Implement `CHARMAP` output.
- [ ] Consider the remaining "[Questions](https://github.com/gbdev/rgbds/issues/606#issuecomment-2266327728)" before finalizing this.

2024-08-04 21:40 UTC, Rangi42 commented on include/asm/symbol.hpp
> +	uint32_t key; // Ordering of the symbol in the state file
```suggestion
	uint32_t defIndex; // Ordering of the symbol in the state file
```

2024-08-04 21:40 UTC, Rangi42 commented on include/asm/output.hpp
> +void out_WriteState(std::string name, std::vector<StateFeature> const &features);
Why is `name` passed by value?

2024-08-04 21:42 UTC, Rangi42 commented on man/rgbasm.1
> +.It Fl s Ar features Ns Op : Ns Ar state_file , Fl \-state Ar features Ns Op : Ns Ar state_file
This isn't in alphabetical order!

2024-08-04 21:45 UTC, Rangi42 commented on man/rgbasm.1
> +.It Fl s Ar features Ns Op : Ns Ar state_file , Fl \-state Ar features Ns Op : Ns Ar state_file
```suggestion
.It Fl s Ar features Ns : Ns Ar state_file , Fl \-state Ar features Ns : Ns Ar state_file
```

2024-08-04 22:08 UTC, ISSOtm submitted a review, later dismissed

2024-08-04 22:08 UTC, ISSOtm commented on src/asm/main.cpp
> +	    "              [-r depth] [-s state] [-W warning] [-X max_errors] <file>\n"
How about `[-s features:state_file]`?

2024-08-04 22:31 UTC, Rangi42 commented on include/asm/output.hpp
> +void out_WriteState(std::string name, std::vector<StateFeature> const &features);
Because `out_WriteState` may reassign it, `name = "<stdout>"`.

2024-08-05 15:56 UTC, ISSOtm requested changes
Very good! This is almost ready for prime time.

2024-08-05 15:56 UTC, ISSOtm commented on man/rgbasm.1
> +.Ql Ic macro Ar name ... Ic endm .
```suggestion
.Ql Ic macro Ar name No ... Ic endm .
```

2024-08-05 15:56 UTC, ISSOtm commented on src/asm/charmap.cpp
> +	std::unordered_map<size_t, std::string> mappings; // keys are indexes of terminal nodes
```suggestion
	std::unordered_map<size_t, std::string> mappings; // keys are indexes of terminal nodes (FIXME: strictly speaking, this is redundant, we could walk the trie instead)
```

2024-08-05 16:26 UTC, ISSOtm approved these changes
Perfect! Thank you *very* much :)

2024-08-05 16:41 UTC, merged