Implement floored `/` and divisor-sign `%` operators
gbdev/rgbds pull request #745
Opened 2021-02-17 01:28 UTC by Rangi42

Fixes #703. Previous discussion and links are there.

The identity `a / b * b + a % b == a` is already true, since truncated division goes with dividend-signed modulus.

With this PR, `a % b == (a + b * k) % b` becomes true for all `k`.

Furthermore, `x % 2**n == x & (2**n - 1)` becomes true.

2021-02-17 02:02 UTC, Rangi42 commented
This also fixes the `**` operator so that `2**30` works. Previously it was doing `base *= base;` when `base` was 65536, which overflowed an `int`.

2021-02-21 02:35 UTC, ISSOtm requested changes
The `div-mod` test looks good, but it only checks the results for RGBASM, not RGBLINK.

2021-02-21 02:35 UTC, ISSOtm commented on src/asm/rgbasm.5
> +.Ic !
I don't think the `.Ic` will apply correctly, due to `!` being a [delimiter](https://mandoc.bsd.lv/man/mdoc.7.html#Delimiters). `\&!` should work around that, as the link suggests.

2021-02-21 20:38 UTC, Rangi42 commented
Updated to test but asm and link functions.

2021-02-21 20:54 UTC, ISSOtm requested changes
No `.out.bin` file is present, therefore RGBLINK isn't actually tested.

2021-02-21 21:04 UTC, Rangi42 commented
You're right; the `math` test was missing its .out.bin file too.

2021-02-21 21:05 UTC, ISSOtm approved these changes
Provided that CI passes, this should be mergeable.

2021-02-21 21:14 UTC, merged