[WIP] Enable address sanitizer in develop builds
gbdev/rgbds pull request #834
Opened 2021-04-16 12:26 UTC by NieDzejkob

WIP, because ASAN detects memory corruption in the test suite. I have minimized the failure
of builtin-overwrite.pipe, the root cause is running a long enough macro while reading from stdin:

```
macro tickle
;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
endm

    tickle
```

2021-04-16 12:32 UTC, ISSOtm requested changes

2021-04-16 12:32 UTC, ISSOtm commented on src/asm/main.c
> +const char* __asan_default_options(void) { return "detect_leaks=0"; }
I'd rather have those be defined in the test files (`export ASAN_OPTIONS="detect_leaks=0"` IIRC)

2021-04-16 12:32 UTC, ISSOtm commented
Since it's WIP, I'm marking this as a draft PR.

2021-04-16 12:34 UTC, NieDzejkob commented
But then any manual runs of rgbasm (for example to run a test file
you're experimenting with) will error out due to leaks.

2021-04-16 12:36 UTC, ISSOtm commented
Fair enough. I guess that's one more incentive to remove the leaks, huh...

I'd like these default functions to be behind a `#ifdef`, so that they won't make it into downstream releases by default.

2021-04-16 14:28 UTC, ISSOtm approved these changes

2021-04-16 14:30 UTC, ISSOtm commented
All that's left now is fixing the bugs; it would be nice if we could fix RGBLINK's memory leaks, too, since it's much simpler than RGBASM and so should be easier to fix. Though, we should probably rather add this to #709's task list.

2021-05-01 10:31 UTC, ISSOtm commented
Tests are now failing on [a heap buf overflow in RGBGFX](https://github.com/gbdev/rgbds/pull/834/checks?check_run_id=2481989846#step:8:5106). RGBGFX is known to be very, very buggy, and leaky as hell. Additionally, [a replacement is in the works](https://github.com/ISSOtm/rsgbgfx), so I suggest that we disable ASan entirely for RGBGFX.

The question then becomes "how do we do this in a portable way"?

2021-05-01 10:43 UTC, ISSOtm commented
(Note: we may want to cherry-pick a985e0ee3d2a195c3fcccbcdff95966e7153b25b directly into `master`, so as to fix the intermittent crashes right away.)

2021-05-01 23:17 UTC, Rangi42 commented
Please do cherry-pick that; it will stop needing to sometimes re-run CI.

2021-05-02 01:38 UTC, ISSOtm commented
Done! dcb8c6966155f556ff186dd21d3fdac610d2baba

2021-05-02 02:37 UTC, Rangi42 commented
04788e15af6878c220602d2248b2b8f5182e96a0 fixes the `heap-buffer-overflow` from RGBGFX. If there are no other such issues, I don't think we need to disable ASAN for it.

2021-05-02 09:05 UTC, ISSOtm commented
```
==1028475==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000155 at pc 0x55d8e633ca8f bp 0x7ffe9c653e70 sp 0x7ffe9c653e60
READ of size 1 at 0x602000000155 thread T0
    #0 0x55d8e633ca8e in create_mapfiles src/gfx/gb.c:228
    #1 0x55d8e6341fef in main src/gfx/main.c:336
tools/pkmncompress gfx/pokemon/front/machoke.2bpp gfx/pokemon/front/machoke.pic
../../rgbgfx  -o gfx/pokemon/back/machokeb.2bpp gfx/pokemon/back/machokeb.png
tools/pkmncompress gfx/pokemon/front/mr.mime.2bpp gfx/pokemon/front/mr.mime.pic
../../rgbgfx  -o gfx/pokemon/back/mr.mimeb.2bpp gfx/pokemon/back/mr.mimeb.png
    #2 0x7f427a283b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #3 0x55d8e633a5dd in _start (/home/issotm/rgbds/rgbgfx+0x1d5dd)

0x602000000155 is located 0 bytes to the right of 5-byte region [0x602000000150,0x602000000155)
allocated by thread T0 here:
    #0 0x7f427ae9a639 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55d8e633a72e in transpose_tiles src/gfx/gb.c:21
    #2 0x55d8e633b60a in raw_to_gb src/gfx/gb.c:59
    #3 0x55d8e6341fcb in main src/gfx/main.c:335
    #4 0x7f427a283b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)

SUMMARY: AddressSanitizer: heap-buffer-overflow src/gfx/gb.c:228 in create_mapfiles
```
Still on the same input file.

2021-05-02 13:55 UTC, Rangi42 commented
`NieDzejkob:asan` has not been rebased to have that fix.

2021-05-02 15:48 UTC, Rangi42 approved these changes

2021-05-02 16:07 UTC, ISSOtm approved these changes

2021-05-02 16:08 UTC, merged