Updated RGBFIX to report when non-zero bytes are overwritten
gbdev/rgbds pull request #861
Opened 2021-04-26 22:39 UTC by GreenAndEievui

Closes #845. 
Updated RGBFIX to report when non-zero bytes are overwritten and updated .err files with the new warning.

2021-04-26 23:29 UTC, Rangi42 commented on src/fix/main.c
> +            fprintf(stderr, "warning: Overwrote one or more non-zero bytes in the %s\n", areaName);
Fix the indentation of `fprintf`. Note that `areaName);` will wrap onto its own line to keep the maximum line length at 100 characters assuming 8-wide tabs. (The `areaName);` would be indented with a extra tab, aligning it inside the `fprintf(` parentheses with `stderr`.)

2021-04-26 23:31 UTC, Rangi42 commented on src/fix/main.c
> +static void nonZeroWarn(uint8_t *rom0, uint16_t startAddr, uint8_t size, char const *areaName) {
I would change this from `nonZeroWarn` to `warnNonZero`, to keep the verb first, like `readBytes`, `writeBytes`, `processFile`, etc.

2021-04-26 23:33 UTC, Rangi42 commented on src/fix/main.c
> +		nonZeroWarn(rom0, 0x14c, 1, "Mask ROM Version number");
Either capitalize `number` or (my personal preference) make all the area names lowercase (except for terms like `Nintendo` or `ROM` where capitals are necessary).

2021-04-26 23:35 UTC, Rangi42 commented on src/fix/main.c
> +            fprintf(stderr, "warning: Overwrote one or more non-zero bytes in the %s\n", areaName);
Also, I agree with @ISSOtm that you don't need an exact non-zero byte count, but "one or more" sounds odd to me for single-byte areas. How about `size > 1 ? "one or more non-zero bytes" : "the non-zero byte"`?

2021-04-26 23:38 UTC, Rangi42 requested changes
Looks like a good first PR! I've commented some suggestions. Also, there's a leftover line `#undef trySeek` that you could remove while editing this file anyway, since nothing defines or needs "`trySeek`".

2021-04-27 01:40 UTC, Rangi42 commented
Thanks for the quick update! The `fprintf` indentation still looks off though; be careful with tabs vs. spaces. (Tabs for indentation, unless you need 1-7 spaces to make a wrapped line align with its above part. Here `size` would go underneath `stderr` so the `s`s line up, like other such long `fprintf` lines in main.c.)

![image](https://user-images.githubusercontent.com/35663410/116171970-d06e4880-a6d7-11eb-85e8-8c646d6395c2.png)

2021-04-27 01:46 UTC, GreenAndEievui commented
Sorry about that, I had my tab width on 4 and didn't think to use spaces to make sure it was exact. It's perfectly aligned now.

2021-04-27 01:49 UTC, Rangi42 commented
A couple more things:

- You're a first-time contributor, so CI tests need manual approval after your commits (a recent security feature). "Code style checking" still fails; please fix the warnings+errors it logs.
- Also in fix/main.asm, can you change `#define or(new, bad)` to `overrideSpec`, along with its usages and `#undef`? `or` is too short to stand out, and it's an [alternative token](https://en.wikipedia.org/wiki/C_alternative_tokens) for `||` from `iso646.h`.

2021-04-27 06:32 UTC, ISSOtm requested changes

2021-04-27 06:32 UTC, ISSOtm commented on src/fix/main.c
> +				size > 1 ? "one or more non-zero bytes" : "the non-zero byte",
```suggestion
				"a non-zero byte",
```
Though at this point it should be merged into the format string anyway.

2021-04-28 15:56 UTC, Rangi42 approved these changes

2021-04-28 15:57 UTC, merged