Make SECTION size overflow non-fatal
gbdev/rgbds pull request #877
Opened 2021-05-03 10:09 UTC by ISSOtm

Fixes #538

2021-05-03 13:15 UTC, Rangi42 requested changes
Add an RGBLINK test case to demonstrate that this can address at least one of the checkbox items in #538. The issue was that bank overflow stops as soon as the bank is overflowed; "max size = 0x4000 bytes, reached 0x4001" sounds like you need to eliminate just one byte, but then you do and get another error on a subsequent line. From the issue discussion I guess this is unavoidable for RGBASM, but not RGBLINK?

2021-05-04 06:29 UTC, ISSOtm commented
Right, this doesn't make any changes to RGBLINK, so it's just a partial fix.

2021-05-04 13:07 UTC, Rangi42 commented
In that case, what it does update is fine.

2021-05-04 13:07 UTC, Rangi42 approved these changes

2021-05-04 13:34 UTC, merged